In [1]:
import numpy as np

In [3]:
np.array([2,4,5,9,15]) #1D array

array([ 2,  4,  5,  9, 15])

In [5]:
a = np.array([15,15,5,3,7]) #Vector
print(a)

[15 15  5  3  7]


In [7]:
type(a)

numpy.ndarray

In [9]:
#2D Array (matrix)
new  = np.array([[13,14,15],[7,9,4]])
print(new)

[[13 14 15]
 [ 7  9  4]]


In [17]:
# 3 D....# Tensor 
np.array([[1,2,3,4],[48,78,96,1],[2,4,5,7],[7,4,8,9],[2,2,2,1],[888,111,54,6]])

array([[  1,   2,   3,   4],
       [ 48,  78,  96,   1],
       [  2,   4,   5,   7],
       [  7,   4,   8,   9],
       [  2,   2,   2,   1],
       [888, 111,  54,   6]])

In [19]:
                     # dtype

In [21]:
                    np.array([11,23,25], dtype=float)

array([11., 23., 25.])

In [23]:
                    np.array([11,12,13], dtype=bool)

array([ True,  True,  True])

In [25]:
                np.array([11,12,13], dtype=complex)

array([11.+0.j, 12.+0.j, 13.+0.j])

In [27]:
    #aray  (similar to range function in python)

In [29]:
    np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [31]:
np.arange(1,25,2)  # strides --> alternate numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [33]:
                        #reshape

In [35]:
#Both of number products should be equal to number of items present inside the array

In [41]:
                 np.arange(1,11).reshape(5,2) # converted to 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
                np.arange(1,11).reshape(2,5) # converted to 2 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [45]:
                np.arange(1,13).reshape(3,4)  #converted to 3 rows and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
                # Ones & Zeros

In [49]:
#You can initialize values and create values ex: in deep learning weight shape

In [51]:
              np.ones((3,4)) # wehave to mention inside tuple

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
               np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
                #Another Type --> random
np.random.rand(3,4)

array([[0.38581786, 0.04521159, 0.29348497, 0.61941584],
       [0.21845644, 0.08027804, 0.04240577, 0.07314659],
       [0.63844368, 0.42315231, 0.92567886, 0.33668789]])

In [69]:
np.empty(2)

array([-3.65833822e-213, -3.73793276e+061])

In [79]:
np.linspace(0,10, num=50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [103]:
a = np.array([1,2,3,4,5,6])
a.shape
print(a)

[1 2 3 4 5 6]


In [101]:
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [99]:
col_vector = a[:, np.newaxis]
col_vector.shape
print(col_vector)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [105]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
#Indexing, slicing

In [107]:
data= np.array([1,2,3])

In [109]:
data[1]

2

In [111]:
data[0:2]

array([1, 2])

In [113]:
data[1:]

array([2, 3])

In [119]:
data[-2:]

array([2, 3])

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [127]:
print(a[a<5])

[1 2 3 4]


In [135]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [137]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [141]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
